// TVK Party Data — Election Promises & Milestones

export const promises = [
  {
    id: 1,
    icon: "👩",
    titleTa: "பெண் சக்தி திட்டம்",
    titleEn: "Women Empowerment",
    descTa: "60 வயதுக்குட்பட்ட குடும்பத் தலைவிகளுக்கு மாதம் ₹2,500 நிதியுதவி வழங்கப்படும்.",
    color: "red",
  },
  {
    id: 2,
    icon: "🎓",
    titleTa: "வேலையில்லா உதவி",
    titleEn: "Unemployment Aid",
    descTa: "பட்டதாரிகளுக்கு ₹4,000 மற்றும் டிப்ளமோ முடித்தவர்களுக்கு ₹2,500 உதவித்தொகை வழங்கப்படும்.",
    color: "yellow",
  },
  {
    id: 3,
    icon: "🇮🇳",
    titleTa: "தமிழர் முன்னுரிமை",
    titleEn: "Tamil Priority",
    descTa: "தமிழ்நாடு அரசுப் பணிகளில் 75% தமிழர்களுக்கே முன்னுரிமை அளிக்கப்படும்.",
    color: "red",
  },
  {
    id: 4,
    icon: "🏗️",
    titleTa: "வட்டியில்லா கல்விக்கடன்",
    titleEn: "Interest-free Loan",
    descTa: "மாணவர்களுக்கு ₹20 லட்சம் வரை வட்டியில்லா கல்விக்கடன் வழங்கப்படும்.",
    color: "yellow",
  },
  {
    id: 5,
    icon: "🔥",
    titleTa: "விலையில்லா சிலிண்டர்",
    titleEn: "Free Cooking Gas",
    descTa: "ஆண்டுக்கு 6 விலையில்லா சமையல் எரிவாயு சிலிண்டர்கள் வழங்கப்படும்.",
    color: "red",
  },
  {
    id: 6,
    icon: "🚌",
    titleTa: "இலவச பேருந்துப் பயணம்",
    titleEn: "Free Bus Travel",
    descTa: "அரசுப் பேருந்துகளில் பெண்களுக்கு கட்டணமில்லாப் பயணம் உறுதி செய்யப்படும்.",
    color: "yellow",
  },
  {
    id: 7,
    icon: "🏫",
    titleTa: "கல்வி ஊக்கத்தொகை",
    titleEn: "Education Support",
    descTa: "அரசுப் பள்ளி மாணவர்களின் தாய்மார்களுக்கு ஆண்டுக்கு ₹15,000 நிதியுதவி வழங்கப்படும்.",
    color: "red",
  },
  {
    id: 8,
    icon: "💍",
    titleTa: "குழந்தை நலப் பெட்டகம்",
    titleEn: "Newborn Kit",
    descTa: "பிறந்த குழந்தைகளுக்கு தங்க மோதிரம் அடங்கிய 24 பொருட்கள் கொண்ட நலப்பெட்டகம்.",
    color: "yellow",
  },
  {
    id: 9,
    icon: "🚫",
    titleTa: "போதையற்ற தமிழகம்",
    titleEn: "Drug-Free TN",
    descTa: "பள்ளி, கல்லூரிகளில் போதைப்பொருள் தடுப்பு மண்டலங்கள் மற்றும் கடும் சட்டங்கள்.",
    color: "red",
  },
  {
    id: 10,
    icon: "🛠️",
    titleTa: "வேலைவாய்ப்பு உறுதி",
    titleEn: "Employment Guarantee",
    descTa: "5 லட்சம் அரசு வேலைகள் மற்றும் 5 லட்சம் இளைஞர்களுக்கு ஊதியத்துடன் தொழிற்பயிற்சி.",
    color: "yellow",
  },
  {
    id: 11,
    icon: "🚜",
    titleTa: "விவசாயிகள் பாதுகாப்பு",
    titleEn: "Farmers Welfare",
    descTa: "நெல் ₹3,500, கரும்புக்கு ₹4,500 ஆதார விலை மற்றும் பயிர்க்கடன் தள்ளுபடி.",
    color: "red",
  },
  {
    id: 12,
    icon: "🧶",
    titleTa: "நெசவாளர் நலன்",
    titleEn: "Weavers Welfare",
    descTa: "ஆண்டுக்கு ₹30,000 நிதியுதவி, இலவச மின்சாரம் மற்றும் ₹10 லட்சம் காப்பீடு.",
    color: "yellow",
  },
  {
    id: 13,
    icon: "👮",
    titleTa: "காவலர் நலன்",
    titleEn: "Police Welfare",
    descTa: "அடிப்படை ஊதியம் ₹25,000, காவலர் நலச் சட்டம் மற்றும் வார விடுமுறை உறுதி.",
    color: "red",
  },
  {
    id: 14,
    icon: "🤝",
    titleTa: "வட்டியில்லா மகளிர் கடன்",
    titleEn: "SHG Interest-free Loans",
    descTa: "மகளிர் சுயஉதவிக் குழுக்களுக்கு ₹5 லட்சம் வரை வட்டியில்லா கடன் வழங்கப்படும்.",
    color: "yellow",
  },
  {
    id: 15,
    icon: "🤖",
    titleTa: "எதிர்கால தொழில்நுட்பம்",
    titleEn: "AI Infrastructure",
    descTa: "AI அமைச்சகம், AI பல்கலைக்கழகம் மற்றும் AI நகரம் உருவாக்கப்படும்.",
    color: "red",
  },
  {
    id: 16,
    icon: "👰",
    titleTa: "திருமண உதவித் திட்டம்",
    titleEn: "Marriage Assistance",
    descTa: "ஏழைப் பெண்களுக்கு ஒரு சவரன் தங்கம் மற்றும் பட்டுச் சேலையுடன் திருமண உதவி.",
    color: "yellow",
  },
  {
    id: 17,
    icon: "🏫",
    titleTa: "காமராஜர் உறைவிடப் பள்ளிகள்",
    titleEn: "Kamarajar Schools",
    descTa: "காமராஜர் பெயரில் 100 சிறப்பு உறைவிடப் பள்ளிகள் மாநிலம் முழுவதும் அமைக்கப்படும்.",
    color: "red",
  },
  {
    id: 18,
    icon: "💰",
    titleTa: "தொழில்முனைவோர் கடன்",
    titleEn: "Entrepreneurship Loans",
    descTa: "புதிய தொழில்முனைவோருக்கு ₹25 லட்சம் வரை வட்டியில்லா கடன் வழங்கப்படும்.",
    color: "yellow",
  },
  {
    id: 19,
    icon: "📑",
    titleTa: "வெளிப்படையான நிர்வாகம்",
    titleEn: "Transparent Admin",
    descTa: "பதவி உயர்வுகளில் லஞ்சம் ஒழிப்பு மற்றும் காலமுறை நிர்வாகம் உறுதி செய்யப்படும்.",
    color: "red",
  },
  {
    id: 20,
    icon: "💼",
    titleTa: "அரசு பணியாளர் நலன்",
    titleEn: "Employees Welfare",
    descTa: "அரசு ஊழியர்களுக்கு முறையான இடமாறுதல் மற்றும் பழைய ஓய்வூதியத் திட்டம் பரிசீலனை.",
    color: "yellow",
  },
];

export const highlights = [
  { titleTa: "சமூக நீதி", titleEn: "Social Justice", icon: "⚖️", desc: "அனைவருக்கும் சமமான வாய்ப்பு மற்றும் மதச்சார்பற்ற சமூக நீதி." },
  { titleTa: "மாநில சுயாட்சி", titleEn: "State Autonomy", icon: "🏛️", desc: "தமிழகத்தின் உரிமைகளை மீட்டெடுத்து, மாநில சுயாட்சியை உறுதி செய்தல்." },
  { titleTa: "பொருளாதார புரட்சி", titleEn: "Economic Revolution", icon: "📈", desc: "2036-க்குள் தமிழகத்தை 1.5 டிரில்லியன் டாலர் பொருளாதாரமாக மாற்றுதல்." },
  { titleTa: "ஊழல் ஒழிப்பு", titleEn: "Anti-Corruption", icon: "🛡️", desc: "வெளிப்படையான நிர்வாகம் மற்றும் ஊழலற்ற நேர்மையான அரசியல்." },
];

export const timeline = [
  { day: "பிப்ரவரி 02, 2024", event: "தமிழக வெற்றி கழகம் கட்சித் தொடக்கம்", eventEn: "Party Formation & Launch" },
  { day: "ஆகஸ்ட் 22, 2024", event: "கட்சிக் கொடி மற்றும் பாடல் அறிமுகம்", eventEn: "Party Flag & Anthem Launch" },
  { day: "அக்டோபர் 27, 2024", event: "முதல் மாநில மாநாடு (விக்கிரவாண்டி)", eventEn: "First State Conference at Vikravandi" },
  { day: "தற்போது", event: "2 கோடி உறுப்பினர் சேர்க்கை முகாம்", eventEn: "2 Crore Membership Drive" },
  { day: "ஏப்ரல் 16, 2026", event: "2026 சட்டமன்றத் தேர்தல் அறிக்கை வெளியீடு", eventEn: "2026 Election Manifesto Launch" },
  { day: "2026", event: "தமிழக சட்டமன்றத் தேர்தல் - வெற்றி இலக்கு", eventEn: "2026 Assembly Elections - Mission Victory" },
];

export const galleryImages = [
  { src: "/images/campaign-rally.jpeg", altTa: "பிரம்மாண்ட பொதுக்கூட்டம்", altEn: "Grand public rally" },
  { src: "/images/campaign-village.png", altTa: "விவசாயிகளுடன் கலந்தாய்வு", altEn: "Meeting farmers" },
  { src: "/images/campaign-youth.png", altTa: "இளைஞர் இயக்கம்", altEn: "Youth movement" },
];
