// TVK Party Data — Election Promises & Milestones

export const promises = [
  {
    id: 1,
    icon: "👩",
    titleTa: "பெண் சக்தி திட்டம்",
    titleEn: "Women Empowerment",
    descTa: "குடும்பத் தலைவிகளுக்கு மாதம் ₹2,500 நிதியுதவி வழங்கப்படும்.",
    color: "red",
  },
  {
    id: 2,
    icon: "🎓",
    titleTa: "வேலையில்லா உதவி",
    titleEn: "Unemployment Aid",
    descTa: "பட்டதாரி இளைஞர்களுக்கு மாதம் ₹4,000 உதவித்தொகை வழங்கப்படும்.",
    color: "yellow",
  },
  {
    id: 3,
    icon: "🇮🇳",
    titleTa: "தமிழர் முன்னுரிமை",
    titleEn: "Tamil Priority",
    descTa: "தமிழ்நாடு அரசுப் பணிகளில் 75% தமிழர்களுக்கே முன்னுரிமை அளிக்கப்படும்.",
    color: "red",
  },
  {
    id: 4,
    icon: "🏗️",
    titleTa: "வட்டியில்லா கல்விக்கடன்",
    titleEn: "Interest-free Loan",
    descTa: "மாணவர்களுக்கு ₹20 லட்சம் வரை வட்டியில்லா கல்விக்கடன் வழங்கப்படும்.",
    color: "yellow",
  },
  {
    id: 5,
    icon: "🔥",
    titleTa: "விலையில்லா சிலிண்டர்",
    titleEn: "Free Cooking Gas",
    descTa: "ஆண்டுக்கு 6 விலையில்லா சமையல் எரிவாயு சிலிண்டர்கள் வழங்கப்படும்.",
    color: "red",
  },
  {
    id: 6,
    icon: "🚌",
    titleTa: "இலவச பேருந்துப் பயணம்",
    titleEn: "Free Bus Travel",
    descTa: "அரசுப் பேருந்துகளில் பெண்களுக்கு கட்டணமில்லாப் பயணம் உறுதி செய்யப்படும்.",
    color: "yellow",
  },
  {
    id: 7,
    icon: "🌾",
    titleTa: "விவசாயி வாரிசு கல்வி",
    titleEn: "Farmers' Education",
    descTa: "சிறு, குறு விவசாயிகளின் பிள்ளைகளுக்கு இலவச தொழில்நுட்ப கல்வி.",
    color: "red",
  },
  {
    id: 8,
    icon: "💍",
    titleTa: "குழந்தை நலப் பெட்டகம்",
    titleEn: "Newborn Kit",
    descTa: "பிறந்த குழந்தைகளுக்கு தங்க மோதிரம் அடங்கிய 24 பொருட்கள் கொண்ட நலப்பெட்டகம்.",
    color: "yellow",
  },
  {
    id: 9,
    icon: "🚫",
    titleTa: "போதையற்ற தமிழகம்",
    titleEn: "Drug-Free TN",
    descTa: "போதைப்பொருட்களை ஒழிக்க கடும் சட்டங்கள் மற்றும் தனிப்பிரிவு உருவாக்கப்படும்.",
    color: "red",
  },
  {
    id: 10,
    icon: "🛠️",
    titleTa: "இளைஞர் தொழிற்பயிற்சி",
    titleEn: "Skill Development",
    descTa: "5 லட்சம் இளைஞர்களுக்கு மாத ஊதியத்துடன் கூடிய தொழிற்பயிற்சி வழங்கப்படும்.",
    color: "yellow",
  },
  {
    id: 11,
    icon: "🚜",
    titleTa: "விவசாயிகள் பாதுகாப்பு",
    titleEn: "Farmers Welfare",
    descTa: "நெல் ₹3,500, கரும்புக்கு ₹4,500 என உயரிய ஆதார விலை உறுதி செய்யப்படும்.",
    color: "red",
  },
  {
    id: 12,
    icon: "🧶",
    titleTa: "நெசவாளர் நலன்",
    titleEn: "Weavers Welfare",
    descTa: "நெசவாளர் குடும்பங்களுக்கு ஆண்டுக்கு ₹30,000 நிதியுதவி வழங்கப்படும்.",
    color: "yellow",
  },
  {
    id: 13,
    icon: "👮",
    titleTa: "காவலர் நலன்",
    titleEn: "Police Welfare",
    descTa: "காவலர்களின் குறைந்தபட்ச அடிப்படை ஊதியம் ₹25,000-ஆக உயர்த்தப்படும்.",
    color: "red",
  },
  {
    id: 14,
    icon: "🤝",
    titleTa: "மக்களின் இல்லந்தேடி சேவை",
    titleEn: "Doorstep Services",
    descTa: "5 லட்சம் இளைஞர்கள் மூலம் வீடுகளுக்கே வந்து அரசு சேவைகள் வழங்கப்படும்.",
    color: "yellow",
  },
  {
    id: 15,
    icon: "🏭",
    titleTa: "தொழில் முற்போக்கு",
    titleEn: "Industrial Growth",
    descTa: "சிறு, குறு தொழில்களுக்கு ₹15,000 கோடி கடன் உத்தரவாத நிதி ஒதுக்கீடு.",
    color: "red",
  },
  {
    id: 16,
    icon: "👰",
    titleTa: "திருமண உதவித் திட்டம்",
    titleEn: "Marriage Assistance",
    descTa: "ஏழைப் பெண்களுக்கு தாலிக்கு தங்கம் மற்றும் திருமண உதவி வழங்கப்படும்.",
    color: "yellow",
  },
  {
    id: 17,
    icon: "🏠",
    titleTa: "நிரந்தர வீடும் வாகனமும்",
    titleEn: "Housing & Mobility",
    descTa: "அனைத்து குடும்பங்களுக்கும் சொந்த வீடும், இருசக்கர வாகனமும் உறுதி செய்யப்படும்.",
    color: "red",
  },
  {
    id: 18,
    icon: "💻",
    titleTa: "டிஜிட்டல் படைப்பாளிகள்",
    titleEn: "Digital Creators",
    descTa: "1.5 லட்சம் டிஜிட்டல் படைப்பாளர்களுக்கு தொழில் தொடங்க நிதியுதவி.",
    color: "yellow",
  },
  {
    id: 19,
    icon: "📑",
    titleTa: "வெளிப்படையான நிர்வாகம்",
    titleEn: "Transparent Admin",
    descTa: "அரசுப் பணி நியமனங்களில் முறைகேடுகளைத் தடுக்க புதிய சட்டம் இயற்றப்படும்.",
    color: "red",
  },
  {
    id: 20,
    icon: "💼",
    titleTa: "அரசு பணியாளர் நலன்",
    titleEn: "Employees Welfare",
    descTa: "அரசு ஊழியர்களுக்கு முறையான இடமாறுதல் மற்றும் பதவி உயர்வு உறுதி செய்யப்படும்.",
    color: "yellow",
  },
];

export const highlights = [
  { titleTa: "சமூக நீதி", titleEn: "Social Justice", icon: "⚖️", desc: "அனைவருக்கும் சமமான வாய்ப்பு மற்றும் மதச்சார்பற்ற சமூக நீதி." },
  { titleTa: "மாநில சுயாட்சி", titleEn: "State Autonomy", icon: "🏛️", desc: "தமிழகத்தின் உரிமைகளை மீட்டெடுத்து, மாநில சுயாட்சியை உறுதி செய்தல்." },
  { titleTa: "மொழி உரிமைகள்", titleEn: "Language Rights", icon: "🗣️", desc: "இருமொழி கொள்கை மற்றும் தமிழ் மொழியின் மேன்மையை பாதுகாத்தல்." },
  { titleTa: "ஊழல் ஒழிப்பு", titleEn: "Anti-Corruption", icon: "🛡️", desc: "வெளிப்படையான நிர்வாகம் மற்றும் ஊழலற்ற நேர்மையான அரசியல்." },
];

export const timeline = [
  { day: "பிப்ரவரி 02, 2024", event: "தமிழக வெற்றி கழகம் கட்சித் தொடக்கம்", eventEn: "Party Formation & Launch" },
  { day: "ஆகஸ்ட் 22, 2024", event: "கட்சிக் கொடி மற்றும் பாடல் அறிமுகம்", eventEn: "Party Flag & Anthem Launch" },
  { day: "அக்டோபர் 27, 2024", event: "முதல் மாநில மாநாடு (விக்கிரவாண்டி)", eventEn: "First State Conference at Vikravandi" },
  { day: "தற்போது", event: "2 கோடி உறுப்பினர் சேர்க்கை முகாம்", eventEn: "2 Crore Membership Drive" },
  { day: "2026", event: "தமிழக சட்டமன்றத் தேர்தல் - வெற்றி இலக்கு", eventEn: "2026 Assembly Elections - Mission Victory" },
];

export const galleryImages = [
  { src: "/images/campaign-rally.jpeg", altTa: "பிரம்மாண்ட பொதுக்கூட்டம்", altEn: "Grand public rally" },
  { src: "/images/campaign-village.png", altTa: "விவசாயிகளுடன் கலந்தாய்வு", altEn: "Meeting farmers" },
  { src: "/images/campaign-youth.png", altTa: "இளைஞர் இயக்கம்", altEn: "Youth movement" },
];
